#!/bin/sh
# Print the Homebrew formula for a release: Formula/omajot.rb in the tap
# renerocksai/homebrew-tap. The release workflow runs it after it publishes
# the binaries and pushes the result to the tap.
#
#   tools/homebrew-formula.sh <version> <SHA256SUMS> [owner/repo]
set -eu

version=${1:?usage: tools/homebrew-formula.sh <version> <SHA256SUMS> [owner/repo]}
sums=${2:?usage: tools/homebrew-formula.sh <version> <SHA256SUMS> [owner/repo]}
repo=${3:-renerocksai/omajot}
base="https://github.com/$repo/releases/download/v$version"

sha() {
  s=$(awk -v f="omajot-$1" '$2 == f { print $1 }' "$sums")
  [ -n "$s" ] || { echo "homebrew-formula.sh: omajot-$1 is not in $sums" >&2; exit 1; }
  echo "$s"
}

cat <<EOF
# Generated by tools/homebrew-formula.sh in $repo for v$version. Do not edit:
# the next release replaces this file.
class Omajot < Formula
  desc "Markdown notes that sync through your own hub over Tailscale"
  homepage "https://renerocks.ai/omajot/"
  version "$version"
  license "MIT"

  on_macos do
    on_arm do
      url "$base/omajot-aarch64-macos"
      sha256 "$(sha aarch64-macos)"
    end
    on_intel do
      url "$base/omajot-x86_64-macos"
      sha256 "$(sha x86_64-macos)"
    end
  end

  on_linux do
    on_arm do
      url "$base/omajot-aarch64-linux"
      sha256 "$(sha aarch64-linux)"
    end
    on_intel do
      url "$base/omajot-x86_64-linux"
      sha256 "$(sha x86_64-linux)"
    end
  end

  def install
    bin.install Dir["omajot-*"].first => "omajot"
  end

  # brew services start omajot: the hub, started at login and restarted if it
  # stops. It reads hub_login (and hub_port, hub_data) from
  # ~/.config/omajot/config.json.
  service do
    run [opt_bin/"omajot", "hub"]
    keep_alive true
    log_path var/"log/omajot-hub.log"
    error_log_path var/"log/omajot-hub.log"
  end

  def caveats
    <<~TEXT
      To run the hub on this computer, write your Tailscale login to
      ~/.config/omajot/config.json once:

        {"hub_login": "you@example.com"}

      Then start the hub and publish it on your tailnet:

        brew services start omajot
        tailscale serve --bg --https=8443 http://127.0.0.1:8787

      The notes are in ~/omajot-data. The log is in
      #{var}/log/omajot-hub.log. Guide: https://renerocks.ai/omajot/get-started.html
    TEXT
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/omajot --version")
  end
end
EOF
